price_kod: 50

##### คนเข้าห้องแพ็ค
อ้อย: 50
มิว: 40
ป้อม: 37.5
หล้า: 42
แบ๋ม: 45
นิด: 45
แหม่ม: 35
ตัน หม่อง: 45
หลาว: 50
เบิร์ด: 45
ภา: 37.5
มิ้น: 40
เนิง: 40
น้องติน: 40
นุช: 40
เอ: 50
หอมใหญ่: 40
ป้อมน้อย: 40
อ้น: 30
เคอ: 40  #เคอ
ยายเหลี่ยน: 30
ลาล่า: 40  #ลาล่า
ลู่: 37.5    #ผัว โรงนอก
บู : 50
บลู : 50
Ole: 50
นวล: 40
เท: 37.5
ผัว ลาล่า: 37.5
มนต์ ญ: 40
มาด ช: 37.5
อำนวย: 50
พี่จูน : 35
อ้ายตา คนทอด: 40
หมวยแลง โสด: 37.5
ไรเย็น ญ: 37.5
สามรัก ช: 37.5
นางลู่ ญ: 37.5
ใจเคอ ช: 37.5
โอเล่: 40
พี่อ๋อย แม่ก๋ง: 37.5
สมหญิง : 35

##### คนกดแผ่น
people_kod:
 - 'หลาว'
 - 'มิ้น'
 - 'เอ'
 - 'เคอ'
 - 'เท'
 - 'ผัว ลาล่า'
 - 'มาด ช'
 - 'หมวยแลง โสด'
 - 'ไรเย็น ญ'
 - 'สามรัก ช'
 - 'นางลู่ ญ'
 - 'ใจเคอ ช'